import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./Provider";
import { Providers } from "@/store/provider";
import { Navbar } from "./components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <Providers>
          <Provider>
            <Navbar title="Mear" />
            {children}
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
